spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost/maternow
spring.datasource.username=root
spring.datasource.password=12345

#mostrando sql no terminal
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.error.include-stacktrace=never

#secret
api.security.token.secret=${JWT_SECRET:123456}

# swagger-ui custom path
springdoc.swagger-ui.path=/swagger-ui.html